name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x] # specify the Node.js version

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up environment variables
        env:
          NEXT_PUBLIC_FIREBASE_API_KEY: ${{ vars.NEXT_PUBLIC_FIREBASE_API_KEY }}
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ vars.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ vars.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
          NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ vars.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
          NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ vars.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
          NEXT_PUBLIC_FIREBASE_APP_ID: ${{ vars.NEXT_PUBLIC_FIREBASE_APP_ID }}
        run: |
          echo "Environment variables are set."
          echo "NEXT_PUBLIC_FIREBASE_API_KEY is set: [${NEXT_PUBLIC_FIREBASE_API_KEY:0:5}...]"
          echo "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN is set: [${{ vars.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}]"
          echo "NEXT_PUBLIC_FIREBASE_PROJECT_ID is set: [${{ vars.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}]"
          echo "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET is set: [${{ vars.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}]"
          echo "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID is set: [${{ vars.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}]"
          echo "NEXT_PUBLIC_FIREBASE_APP_ID is set: [${{ vars.NEXT_PUBLIC_FIREBASE_APP_ID }}]"

      - name: Install dependencies
        run: npm install

      - name: Print Environment Variables Before Build
        run: printenv | grep NEXT_PUBLIC_

      - name: Build the project
        env:
          NEXT_PUBLIC_FIREBASE_API_KEY: ${{ vars.NEXT_PUBLIC_FIREBASE_API_KEY }}
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ vars.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ vars.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
          NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ vars.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
          NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ vars.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
          NEXT_PUBLIC_FIREBASE_APP_ID: ${{ vars.NEXT_PUBLIC_FIREBASE_APP_ID }}
        run: npm run build
